### PR TITLE
[JENKINS-68510] Fix JAXBContext classLoader context

### PR DESCRIPTION
**Pull request by alecharp**
see [JENKINS-68510](https://issues.jenkins.io/browse/JENKINS-68510).
Follow up of #21.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by basil** [comment]
CC @marcrohlfs

**Comment by basil** [comment]
Hi @bonnetb and @nazarovkv, if you are still using this plugin, would you be able to test the latest release (2.1) with a recent LTS release of Jenkins running on Java 11 and confirm that the plugin is working? If so, thank you in advance!

**Comment by nazarovkv** [comment]
> Hi @bonnetb and @nazarovkv, if you are still using this plugin, would you be able to test the latest release (2.1) with a recent LTS release of Jenkins running on Java 11 and confirm that the plugin is working? If so, thank you in advance!

Will do next week ;-)

**Comment by basil** [comment]
Hi @nazarovkv, if you are still interested in testing this plugin, would you be able to test the latest release (2.1) with a recent LTS release of Jenkins running on Java 11 and confirm that the plugin is working? If so, thank you in advance!

**Comment by basil** [comment]
Hi @nazarovkv, were you able to test the latest release?

**Pull request merged**
