### PR TITLE
JENKINS-38619

### PR DESCRIPTION
**Pull request by bonnetb**
See : JENKINS-38619 : "Maven metadata plugin does not work with jenkins pipelineam value to pipeline"

Here is an excerpt from my Jenkinsfile :   

```
 script {
    def userInput = input(id:'userInput', message: 'Choose a version please', parameters: [[$class: 'MavenMetadataParameterDefinition', artifactId: 'my-precious-artifact', classifier: '', credentialsId: 'a12eee-1514141-false-id-11111111', currentArtifactInfoLabel: '', currentArtifactInfoPattern: '', currentArtifactInfoUrl: '', defaultValue: '', description: '', groupId: 'fr.my.group', maxVersions: '', name: 'version', packaging: 'jar', repoBaseUrl: 'http://mymavenrepository.com/repository/releases', sortOrder: 'DESC',versionFilter: '']], submitter:'admin' ,submitterParameter: 'submittedBy');
    print(userInput)
    }
```

Here is the log I got (choosing an 1.5.2 version in the drop down menu): 
```
[Pipeline] script
[Pipeline] {
[Pipeline] input
Input requested
Approved by admin
[Pipeline] echo
{submittedBy=admin, version=1.5.2}
```
Without the fix, I got {submitteBy=admin, version=null}. So the fix makes version param available.

### CODE REVIEW

**Comment by CSchulz** [comment]
Tests doesn't build any more:

```
Tests in error: 
eu.markov.jenkins.plugin.mvnmeta.MavenMetadataParameterDefinitionBackwardCompatibilityTest.testReadResolve(eu.markov.jenkins.plugin.mvnmeta.MavenMetadataParameterDefinitionBackwardCompatibilityTest)
  Run 1: MavenMetadataParameterDefinitionBackwardCompatibilityTest.testReadResolve » Reactor
  Run 2: MavenMetadataParameterDefinitionBackwardCompatibilityTest.testReadResolve » Reactor
  Run 3: MavenMetadataParameterDefinitionBackwardCompatibilityTest.testReadResolve » Reactor
  Run 4: MavenMetadataParameterDefinitionBackwardCompatibilityTest.testReadResolve » Reactor
  Run 5: MavenMetadataParameterDefinitionBackwardCompatibilityTest.testReadResolve » Reactor

  FailedTest.org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite » IncompatibleClassChange
```

**Comment by bonnetb** [comment]
Hi,
after upgrading dependencies, plugins and fixing a CR character issue in tests, tests run again.
Regards

**Comment by marcrohlfs** [comment]
Hi @bonnetb,

many thanks for this PR! Just found some time to review it. Unfortunately it still doesn't seem to build - on my environment. When it run ``mvn install``, it fails due to Java 8 Javadoc problems. Didn't You experience that?

I noticed that there's another problem with Java 8, that exists already on the master branch. I'll think I'll work on a proper Java and Jenkins upgrade for this plugin now, as well as fixing [JENKINS-38978](https://issues.jenkins-ci.org/browse/JENKINS-38978) - which I think You already may have solved. Would be nice if You could review may upcoming PR, too, and we could release everything together afterwards.

Kind regards
Marc

P.S.: Some more information in the commit comments would be helpful to get a better understanding of the commits' contents. Thanks :-)

**Comment by bonnetb** [comment]
Hi @marcrohlfs,
Thank you for your review.
I had that Javadoc 8 issue too. It is due to a lint check that was added with Java 8. I have just committed a change to get rid of that check.
I also had findbugs errors, so I changed source code (same commit) to make it ok according to findbugs.
Please tell me when you publish your PR so that I can have a look at it.
Regards

**Comment by marcrohlfs** [comment]
Hi @bonnetb,

I addressed all the update relevant changes when solving [JENKINS-38978](https://issues.jenkins-ci.org/browse/JENKINS-38978). Please have a look at pull request #14.

I solved some part a little different than You did. This will (unfortunately) mean that You'll probably have to apply Your changes to in order to get them merged. Maybe it'll be easier for You to create a new pull request (after mine is merged) and just cherry-pick Your 1st commit.

But first let's see if there aren't any concerns about my PR ... ;-)

Kind regards
Marc

**Comment by CSchulz** [comment]
Hello,

how far is the progress with the Java 8 update? I have still issues with building it against Java 8.

**Comment by CSchulz** [comment]
I have checked the PR against the master and the only change seems to be the override for getValue:

```
  @Override
  public Object getValue() {
    return getVersion();
  }
```

**Comment by marcrohlfs** [comment]
Hi @bonnetb,

many thanks again :)

One more question: Do You already have a Jenkins job using pipeline DSL with this plugin? Could You provide the _config.xml_ for such a test job? I'd like to add a pipeline test job to the development workspace (see `src/dev/assets/work/jobs`).

In the meantime I'll merge the PR and release the plugin.

Regards
Marc

**Comment by bonnetb** [comment]
Hi @marcrohlfs ,
I create a new PR to provide a sample config.xml
See https://github.com/jenkinsci/maven-metadata-plugin/pull/15

**Pull request merged**
